import './globals.css';
import { Prompt } from 'next/font/google'

const prompt = Prompt({ subsets: ['thai'], weight: ['400', '700'] }); 

export const metadata = {
  title: 'Dashboard App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body className={prompt.className}> 
        {children}
      </body>
    </html>
  );
}